FROM python:3.11-slim
WORKDIR /app
COPY scripts/aggregate_nvml.py ./
COPY scripts/aggregate_nvml_energy.py ./
COPY scripts/aggregate_variorum.py ./
COPY scripts/run.sh ./
RUN pip install --no-cache-dir pandas numpy
CMD ["bash", "run.sh"]