apiVersion: 1

datasources:
  - name: PostgreSQL-Energy
    type: grafana-postgresql-datasource
    uid: bepxmpopbv668b
    access: proxy
    url: postgres_db:5432
    database: energy_analysis
    user: grafana_user
    secureJsonData:
      password: super_secret_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
